### ISSUE TITLE
Need more strictness

### ISSUE THREAD

**Issue by robinp** [edsko/ghc-dump-tree#2]
For the simple test

```
module A where
fun = 1
```

I get a panic. Replacing all 'return $' with 'return $!' forces the evals to happen inside the ghandle, and prints out the tree ok. (Thankfully Aeson.Value is strict in the fields already).

**Comment by edsko** [comment]
Is this addressed by https://github.com/edsko/ghc-dump-tree/pull/3 ?

**Comment by robinp** [comment]
No, I still needed the replace for GHC 7.6.3 and 7.8.4 - but 7.10.2 was already fine. Will send a PR with some fixes.
