### ISSUE TITLE
Provide a library as well as an executable

### ISSUE THREAD

**Issue by JPMoresmau** [edsko/ghc-dump-tree#5]
After discussing it with @alanz, we think it may be beneficial to have ghc-dump-tree as a library and exposed via a haskell-ide-engine plugin. I will try to work on that and will do a pr when ready. Let me know if I should be aware of any pitfalls.

**Comment by edsko** [comment]
Sure, sounds good. Can't really think of any pitfalls except the usual one when using GHC-as-a-library, which is if you depend on something GHC-the-library depends on you're stuck with the version GHC is compiled against. But you knew that already :)

**Comment by edsko** [comment]
Closed in #6.
